### ISSUE TITLE
Download model script 

### ISSUE THREAD

**Issue by kryzhikov** [zengxianyu/sketchedit#1]
Hello, Great Work! 

Only one question, where can I get pertained models? 

Readme says: 
```bash
chmod +x download/*
./download/download_model.sh
```

But there is no such directory or script in repository.

**Comment by virtualramblas** [comment]
Also, there is no reference to links where one can download the pre-trained models manually.

**Comment by zengxianyu** [comment]
it's updated

**Comment by virtualramblas** [comment]
Thank you @zengxianyu
